# LiteLLM Proxy config — generated by Terraform templatefile()
# DO NOT edit manually. Edit infra/config.yaml.tpl and re-apply Terraform.

model_list:
%{ for name, model in models ~}
%{ if model.responses_only ~}
  # Responses-only model (e.g. codex) — uses /v1/preview endpoint via azure/responses/ prefix
  - model_name: ${name}
%{ if try(model.base_model, null) != null || try(model.input_cost_per_token, null) != null || try(model.output_cost_per_token, null) != null || try(model.cache_read_input_token_cost, null) != null ~}
    model_info:
%{ if try(model.base_model, null) != null ~}
      base_model: ${model.base_model}
%{ endif ~}
%{ if try(model.input_cost_per_token, null) != null ~}
      input_cost_per_token: ${model.input_cost_per_token}
%{ endif ~}
%{ if try(model.output_cost_per_token, null) != null ~}
      output_cost_per_token: ${model.output_cost_per_token}
%{ endif ~}
%{ if try(model.cache_read_input_token_cost, null) != null ~}
      cache_read_input_token_cost: ${model.cache_read_input_token_cost}
%{ endif ~}
%{ endif ~}
    litellm_params:
      model: azure/responses/${name}
      api_base: os.environ/AZURE_AI_API_BASE_${upper(region_short[model.region])}
      api_key: os.environ/AZURE_AI_API_KEY_${upper(region_short[model.region])}
      api_version: preview
%{ else ~}
  - model_name: ${name}
    model_info:
      mode: chat
%{ if try(model.base_model, null) != null ~}
      base_model: ${model.base_model}
%{ endif ~}
%{ if try(model.input_cost_per_token, null) != null ~}
      input_cost_per_token: ${model.input_cost_per_token}
%{ endif ~}
%{ if try(model.output_cost_per_token, null) != null ~}
      output_cost_per_token: ${model.output_cost_per_token}
%{ endif ~}
%{ if try(model.cache_read_input_token_cost, null) != null ~}
      cache_read_input_token_cost: ${model.cache_read_input_token_cost}
%{ endif ~}
    litellm_params:
      model: azure/${name}
      api_base: os.environ/AZURE_AI_API_BASE_${upper(region_short[model.region])}
      api_key: os.environ/AZURE_AI_API_KEY_${upper(region_short[model.region])}
      api_version: os.environ/AZURE_AI_API_VERSION
%{ endif ~}
%{ endfor ~}

# Prevent clients from overriding sensitive provider fields at request-time
litellm_settings:
  drop_params: true
  json_logs: true

  # Usage tracking callback - CustomLogger instance for async success/failure events
  callbacks: usage_callback.proxy_handler_instance

# General proxy settings
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

  # Custom auth handler — validates Bearer tokens against API_KEYS env var.
  # Runs before LiteLLM's built-in master_key check and replaces it entirely.
  # The handler also accepts LITELLM_MASTER_KEY so admin operations still work.
  # File is copied to /app/custom_auth.py by the container entrypoint at startup.
  custom_auth: custom_auth.user_api_key_auth

  store_model_in_db: false
  disable_spend_logs: true
  disable_spend_updates: true
  disable_reset_budget: true

  # Prevent master key hash write attempts against non-existent DB
  disable_adding_master_key_hash_to_db: true
  # Allow requests if LiteLLM probes for a DB and finds none
  allow_requests_on_db_unavailable: true

  # forward_client_headers_to_llm_api omitted — default (false/None) is correct;
  # proxy Authorization header is never forwarded to upstream regardless.
  # timeout omitted — let provider defaults apply; reasoning models can exceed 60s.
