# LiteLLM Proxy config — generated by Terraform templatefile()
# DO NOT edit manually. Edit infra/config.yaml.tpl and re-apply Terraform.

model_list:
%{ for name, model in models ~}
  - model_name: ${name}
    litellm_params:
      model: azure/${name}
      api_base: os.environ/AZURE_AI_API_BASE_${upper(region_short[model.region])}
      api_key: os.environ/AZURE_AI_API_KEY_${upper(region_short[model.region])}
      api_version: os.environ/AZURE_AI_API_VERSION
%{ endfor ~}

# Prevent clients from overriding sensitive provider fields at request-time
litellm_settings:
  drop_params: true

# General proxy settings
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  store_model_in_db: false
  disable_spend_logs: true
  disable_spend_updates: true
  disable_reset_budget: true

  ## TODO: Check these — enabling breaks auth
  # forward_client_headers_to_llm_api: false
  # disable_adding_master_key_hash_to_db: true
  # allow_requests_on_db_unavailable: true
  # timeout: 60
